CREATE TABLE USERS
(
  id BIGINT NOT NULL AUTO_INCREMENT,
  login VARCHAR(25) NOT NULL,
  password VARCHAR(30) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE BOOKS
(
id BIGINT NOT NULL AUTO_INCREMENT,
ins INTEGER NOT NULL,
name VARCHAR(30) NOT NULL,
author VARCHAR(20) NOT NULL,
user_id BIGINT,
PRIMARY KEY (id),
FOREIGN KEY (user_id) REFERENCES USERS(id)
);
